sudo: required

language: go

services:
  - docker

script:
  - cd docs && make docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs/_build
  on:
    branch: master

